---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# EcoPast

<!-- badges: start -->
<!-- badges: end -->

An R package for ecological and macroecological analyses of the deep time fossil record

## Installation

EcoPast (GPL-2) relies on some functions provided by other packages. Some of these packages cannot be directly installed along with EcoPast because they are distributed under different license types. Please notice, before installing EcoPast, make sure you have installed the following packages:

SDMTools (last version) available at https://cran.r-project.org/src/contrib/Archive/SDMTools/.

chronosphere and rangeBuilder, available on CRAN, can be installed by means of the common installation procedure in R.

## Important Note 
EcoPast uses dependencies with ACM license, we address users to the authors of packages rangeBuilder, alphahull, and tripack for commercial use.

DOI for citing the code:
https://zenodo.org/badge/latestdoi/253762735

